"""empty message

Revision ID: c63bb0e3de4a
Revises: 4171b1a82bdc
Create Date: 2020-09-15 22:04:48.155822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63bb0e3de4a'
down_revision = '4171b1a82bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('venue_id', sa.Integer(), nullable=False),
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.DateTime, nullable=False),
                    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
                    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
